### ISSUE TITLE
Fuck You

### ISSUE THREAD

**Issue by HanzoDev1375** [Nexus-IDE/Nexus-IDE#4]
![Screenshot_2024-10-14-01-24-54-728_bin mt plus](https://github.com/user-attachments/assets/80ac2d17-857e-4efc-8135-6c4c52f59d9a)

Why did you use my class, I wrote this class, delete it, you filthy bastard

**Comment by trindadedev13** [comment]
please be respectful, and no you didn't write that, so bye.

**Comment by OSilvaDev** [comment]
Hello, You have a problem with me, that's fine. But don't come trying to tarnish my project. This class was in tyron1223's project, I just modified it to use it in my project correctly. Furthermore, if you are messing with my project files, it is because YOU are doing it just to tarnish my project.

**Comment by OSilvaDev** [comment]
Hi, it wasn't you who made the class, it was tyron12233. So be respectful, bye.
